packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  '@sentry/cli': true
  '@shopify/react-native-skia': true
  esbuild: true
  msw: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.20'
  - '@expo/env@2.4.3'
  - '@expo/fingerprint@0.20.11'
  - '@expo/metro-config@57.0.12'
  - '@nestjs/swagger@12.0.1'
  - '@sentry/core@10.72.0'
  - '@sentry/nestjs@10.72.0'
  - '@sentry/node-core@10.72.0'
  - '@sentry/node@10.72.0'
  - '@sentry/opentelemetry@10.72.0'
  - '@sentry/server-utils@10.72.0'
  - expo-constants@57.0.16
  - expo-font@57.0.2
  - expo@57.0.18
  - zod@4.5.2
